"""
Education section.
Static: school, degree, GPA, dates.
Generated by K2: TA/RA bullets, coursework line.
"""
from __future__ import annotations
from graph import queries
from .. import llm
from ..utils import tex_escape


EDUCATION_SYSTEM = """You are writing the Education section bullets for a CS graduate student's resume.
You rewrite TA, RA, and coursework lines to naturally include JD keywords.

STRICT RULES:
- GPA values must appear EXACTLY as given — never change them
- School names, degree names, dates — DO NOT change
- TA student count must remain "120+"
- Bullets must be concise (max 1.5 lines each when printed)
- Do not add fake courses or fake research topics
- Weave in 2-4 JD keywords naturally per bullet
- Coursework line: comma-separated course names only, no bullet point formatting

Output JSON with exactly these keys:
{
  "nyu_ta_bullet": "<rewritten TA bullet text, no \\item>",
  "nyu_ra_bullet": "<rewritten RA bullet text, no \\item>",
  "nyu_courses": "<comma-separated course names>",
  "manipal_bullet": "<rewritten Manipal honors bullet, no \\item>"
}"""


def render(jd_analysis: dict, selection: dict) -> str:
    edu_list = queries.get_education()
    nyu = next(e for e in edu_list if "New York" in e["school"])
    manipal = next(e for e in edu_list if "Manipal" in e["school"])

    all_keywords = (
        jd_analysis.get("required_keywords", [])
        + jd_analysis.get("preferred_keywords", [])
    )
    added_courses = selection.get("courses_to_add", [])
    base_courses = list(nyu["courses"]) + [c for c in added_courses if c not in nyu["courses"]]

    user_prompt = f"""JD KEYWORDS TO WEAVE IN: {', '.join(all_keywords[:20])}
ROLE TYPE: {jd_analysis.get('role_type', '')}

BASE TA BULLET: {nyu['honors'][0]}
BASE RA BULLET: {nyu['honors'][1]}
BASE COURSES: {', '.join(base_courses)}
BASE MANIPAL BULLET: {manipal['honors'][0]}

GPA VALUES (IMMUTABLE): NYU = {nyu['gpa']}/{nyu['gpa_scale']}, Manipal = {manipal['gpa']}/{manipal['gpa_scale']}
TA STUDENT COUNT (IMMUTABLE): 120+"""

    generated = llm.call_json(EDUCATION_SYSTEM, user_prompt)

    ta = tex_escape(generated.get("nyu_ta_bullet", nyu["honors"][0]))
    ra = tex_escape(generated.get("nyu_ra_bullet", nyu["honors"][1]))
    courses = tex_escape(generated.get("nyu_courses", ", ".join(base_courses)))
    manipal_bullet = tex_escape(generated.get("manipal_bullet", manipal["honors"][0]))

    return rf"""
    \section{{Education}}

        \begin{{twocolentry}}{{
            Expected: {nyu['end_date']}, CGPA: {nyu['gpa']}/{nyu['gpa_scale']}
        }}
            \textbf{{{nyu['school']}}}, {nyu['degree']} in {nyu['field']} -- {nyu['location']}\end{{twocolentry}}

        \vspace{{0.05 cm}}
        \begin{{onecolentry}}
            \begin{{highlights}}
                \item {ta}
                \item {ra}
                \item \textbf{{Relevant Coursework:}} {courses}
            \end{{highlights}}
        \end{{onecolentry}}

        \vspace{{0.15 cm}}

        \begin{{twocolentry}}{{
            {manipal['start_date']} -- {manipal['end_date']}, CGPA: {manipal['gpa']}/{manipal['gpa_scale']}
        }}
            \textbf{{{manipal['school']}}}, {manipal['degree']} in {manipal['field']} -- {manipal['location']}\end{{twocolentry}}

        \vspace{{0.05 cm}}
        \begin{{onecolentry}}
            \begin{{highlights}}
                \item {manipal_bullet}
            \end{{highlights}}
        \end{{onecolentry}}
"""
