"""
Professional Experience section.
Static: company, location, dates.
Generated by K2: title variant + bullets (one K2 call per experience).
Metrics are injected from the graph — K2 cannot change them.
"""
from __future__ import annotations
from graph import queries
from .. import llm
from ..utils import tex_escape


_BULLET_SYSTEM = """You are rewriting work experience bullet points for a software engineer resume.

RULES:
1. LOCKED METRICS — copy each metric value EXACTLY character for character.
   If the metric says "95%", your bullet MUST contain "95%". No paraphrasing, no omissions.
2. Do not invent new numbers or percentages beyond the locked list.
3. Each bullet starts with a strong past-tense action verb.
4. Output raw strings only — no LaTeX, no markdown, no bullet symbols.
5. Write EXACTLY 3 bullets. The resume must fit on one page — no more than 3 per experience.
6. Weave in 3-5 JD keywords naturally across the bullets.
7. LINE LENGTH TARGET: each bullet should be approximately 120-137 characters long including spaces.
   Write dense, information-packed bullets that fill a full printed line.
   Avoid short bullets under 90 characters — expand with relevant tech context instead."""


def _build_bullet_prompt(
    exp: dict,
    metrics: list[dict],
    jd_analysis: dict,
    title: str,
) -> str:
    all_kw = (
        jd_analysis.get("required_keywords", [])
        + jd_analysis.get("preferred_keywords", [])
    )
    metric_strings = [f'"{m["value"]}"' for m in metrics]
    metric_labels  = [f"{m['label']}: {m['value']}" for m in metrics]
    return f"""COMPANY: {exp['company']}
ROLE TITLE: {title}
ROLE TYPE: {jd_analysis.get('role_type', '')}
COMPANY CONTEXT: {jd_analysis.get('company_name', '')} — {jd_analysis.get('jd_summary', '')}

LOCKED METRIC VALUES — copy each EXACTLY into a bullet (character-for-character):
{chr(10).join(f'  • {lbl}  →  your bullet MUST contain the exact text {val}' for lbl, val in zip(metric_labels, metric_strings))}

JD KEYWORDS TO WEAVE IN (3-5 most relevant):
{', '.join(all_kw[:20])}

BASE BULLETS (factual foundation — rewrite for this JD):
{chr(10).join(f'{i+1}. {b}' for i, b in enumerate(exp['bullets']))}

Output a JSON array of bullet strings (3-5 bullets):
["bullet 1", "bullet 2", ...]"""


def _extract_tech(text: str) -> list[str]:
    """Heuristic: extract capitalized tech terms from bullet text."""
    import re
    return re.findall(r'\b(?:Python|Java|React|TypeScript|JavaScript|Go|Node\.js|PostgreSQL|SQL|Docker|Kubernetes|AWS|CI/CD|YOLO|PyTorch|TensorFlow|FastAPI|Firebase|Flutter)\b', text)


def _render_experience(exp: dict, title: str, bullets: list[str]) -> str:
    bullet_items = "\n                ".join(
        f"\\item {tex_escape(b)}" for b in bullets
    )
    return rf"""
        \begin{{twocolentry}}{{
            {exp['start_date']} -- {exp['end_date']}
        }}
            \textbf{{{tex_escape(title)}}}, {tex_escape(exp['company'])} -- {tex_escape(exp['location'])}\end{{twocolentry}}

        \vspace{{0.05 cm}}
        \begin{{onecolentry}}
            \begin{{highlights}}
                {bullet_items}
            \end{{highlights}}
        \end{{onecolentry}}

        \vspace{{0.15 cm}}
"""


def _inject_missing_metrics(bullets: list[str], metrics: list[dict]) -> list[str]:
    """Append any metric value that Gemma omitted directly into the most relevant bullet."""
    if not bullets or not metrics:
        return bullets
    combined = " ".join(bullets)
    missing = [m for m in metrics if m["value"] not in combined]
    if not missing:
        return bullets
    # Append all missing values to the last bullet as a parenthetical
    suffix = "; ".join(f"{m['label']}: {m['value']}" for m in missing)
    bullets = list(bullets)
    bullets[-1] = bullets[-1].rstrip(".") + f" ({suffix})."
    return bullets


def render(jd_analysis: dict, selection: dict) -> str:
    experiences = queries.get_experiences()

    title_map = {
        "exp_hpe": selection.get("hpe_title", "Software Engineer Intern"),
        "exp_ongc": selection.get("ongc_title", "Software Engineer Intern"),
        "exp_onfees": "Software Engineer Intern",
    }

    sections = ["\n    \\section{Professional Experience}\n"]

    for exp in experiences:
        metrics = queries.get_experience_metrics(exp["id"])
        title = title_map.get(exp["id"], exp["title"])

        prompt = _build_bullet_prompt(exp, metrics, jd_analysis, title)
        bullets = llm.call_json_list(_BULLET_SYSTEM, prompt)

        if not bullets:
            bullets = exp["bullets"]

        bullets = _inject_missing_metrics(bullets, metrics)
        bullets = bullets[:3]  # hard cap — 3 experiences × 3 bullets = 1 page
        sections.append(_render_experience(exp, title, bullets))

    return "".join(sections)
