"""
Projects section.
Static: project name (never changes).
Generated by K2: subtitle framing, tech stack line, bullets per project.
Locked metrics are injected from the graph — K2 cannot omit them.
"""
from __future__ import annotations
from graph import queries
from .. import llm
from ..utils import tex_escape


_PROJECT_SYSTEM = """You are writing ONE project entry for a software engineer resume.

RULES:
1. Project name is fixed — do not change it.
2. LOCKED METRIC VALUES must appear character-for-character in the bullets.
   If a metric value is "96.8%", one bullet MUST contain the exact text "96.8%".
   Do NOT round, paraphrase, or omit any metric value.
3. Do not invent new numbers or percentages.
4. Subtitle: 3-8 words describing what the project IS (role-specific framing).
5. tech_line: 4-6 most relevant technologies, comma-separated.
6. bullets: exactly 3 bullets. Strong action verbs.
7. Weave in 2-3 JD keywords naturally.
8. LINE LENGTH TARGET: each bullet should be approximately 120-137 characters long including spaces.
   Write dense, information-packed bullets that fill a full printed line.
   Avoid short bullets under 90 characters — add implementation detail or tech context instead.

Output ONLY this JSON (no other text):
{
  "subtitle": "<3-8 word framing>",
  "tech_line": "<Tech1, Tech2, Tech3>",
  "bullets": ["bullet 1", "bullet 2", "bullet 3"]
}"""


def _generate_one_project(p: dict, jd_analysis: dict) -> dict:
    """Call K2 for a single project — keeps prompts small and avoids timeouts."""
    all_kw = (
        jd_analysis.get("required_keywords", [])
        + jd_analysis.get("preferred_keywords", [])
    )
    metrics = p.get("metrics", [])
    metric_lines = "\n".join(
        f'  • {m["label"]}: {m["value"]}  →  bullet MUST contain exact text "{m["value"]}"'
        for m in metrics
    ) if metrics else "  none"

    user_prompt = f"""PROJECT NAME (do not change): {p['name']}
CATEGORY: {p['category']}
DESCRIPTION: {p['description']}
TECH STACK: {', '.join(p['tech'])}
GITHUB: {p.get('github', '')}

LOCKED METRIC VALUES (copy each value exactly into a bullet):
{metric_lines}

JD ROLE TYPE: {jd_analysis.get('role_type', '')}
JD COMPANY: {jd_analysis.get('company_name', '')}
JD KEYWORDS TO WEAVE IN (pick 2-3): {', '.join(all_kw[:12])}"""

    try:
        return llm.call_json(_PROJECT_SYSTEM, user_prompt, max_tokens=131072)
    except Exception:
        return {}


def _inject_missing_metrics(bullets: list[str], metrics: list[dict]) -> list[str]:
    """Append any metric value Gemma omitted directly into the last bullet."""
    if not bullets or not metrics:
        return bullets
    combined = " ".join(bullets)
    missing = [m for m in metrics if m["value"] not in combined]
    if not missing:
        return bullets
    suffix = "; ".join(f"{m['label']}: {m['value']}" for m in missing)
    bullets = list(bullets)
    bullets[-1] = bullets[-1].rstrip(".") + f" ({suffix})."
    return bullets


def render(jd_analysis: dict, selection: dict) -> str:
    selected_ids = selection.get("selected_project_ids", [])
    if not selected_ids:
        return ""

    proj_data: dict[str, dict] = {}
    for pid in selected_ids:
        p = queries.get_project_with_metrics(pid)
        if p:
            proj_data[pid] = p

    parts = ["\n    \\section{Projects}\n"]
    for pid in selected_ids:
        p = proj_data.get(pid)
        if not p:
            continue

        gen = _generate_one_project(p, jd_analysis)
        subtitle = tex_escape(gen.get("subtitle", p["description"][:50]))
        tech_line = tex_escape(gen.get("tech_line", ", ".join(p["tech"][:5])))
        bullets = gen.get("bullets") or [p["description"]]
        bullets = _inject_missing_metrics(bullets, p.get("metrics", []))
        bullets = bullets[:3]  # hard cap at 3

        bullet_items = "\n                ".join(
            f"\\item {tex_escape(b)}" for b in bullets
        )

        github = p.get("github", "")
        github_url = f"https://{github}" if github and not github.startswith("http") else github
        name_tex = (
            rf"\href{{{github_url}}}{{{tex_escape(p['name'])}}}"
            if github_url else tex_escape(p["name"])
        )

        parts.append(rf"""
        \begin{{onecolentry}}
            \textbf{{{name_tex} -- {subtitle}}} | {tech_line}
        \end{{onecolentry}}

        \vspace{{0.05 cm}}
        \begin{{onecolentry}}
            \begin{{highlights}}
                {bullet_items}
            \end{{highlights}}
        \end{{onecolentry}}

        \vspace{{0.15 cm}}
""")

    return "".join(parts)
